### ISSUE TITLE
Can not see the bars

### ISSUE THREAD

**Issue by billyjoker** [dzolnai/ExoVisualizer#2]
Hi, i can listen the audio but the central white line does not animate. Also i get an exception when calling invalidate()

`only the original thread that created a view hierarchy can touch its views.`

**Comment by dzolnai** [comment]
Hi!
Depending on the audio stream, the output values might be too low. You can increase/decrease the sensitivity by changing maxConst in FFTBandView: https://github.com/dzolnai/ExoVisualizer/blob/master/app/src/main/java/com/egeniq/exovisualizer/FFTBandView.kt#L35

Do you get the exception on the unmodified library code?

**Comment by billyjoker** [comment]
Hi, i did not modify your code, but i've figured out that your call to invalidate() must to be inside onDraw method to work properly, i do not know the reason but when i moved that call it started to work!!

One more question, i see some bars (mid freqs) too high compared to the other bands, they go so high until the top of the screen, any idea to smooth that peaks?

Thanks in advance!!

**Comment by dzolnai** [comment]
Yes, by changing the maxConst I linked in my previous answer.

**Comment by billyjoker** [comment]
Oh sorry, i've see it, but i meant that i'd like to decrease that high peaks without performing decreasing the peaks of the other bands

**Comment by dzolnai** [comment]
Oh like that. You could try executing a square function and then reducing the maxConst, that would reduce the higher bars.

**Comment by Net-time** [comment]
Same problem as original post and fixed as suggested (Android Studio)
Moved "invalidate" as belown in FFTBandView:
`            arraycopy(fft, 2, this.fft, 0, size)
        }
    }

    override fun onDraw(canvas: Canvas) {
        super.onDraw(canvas)
        drawAudio(canvas)
        // By calling invalidate, we request a redraw.
        invalidate()
    }
}`

Needs to be in "override"

**Comment by dzolnai** [comment]
@Net-time your solution seems to improve the drawing quite a bit, so I added it to the code.
Thanks for your feedback.
