### ISSUE TITLE
Using recorded audio 

### ISSUE THREAD

**Issue by akkale** [dzolnai/ExoVisualizer#4]
I want to develop an app wich can record an audio and play it by showing it on the visualizer. It could be a live recorder or just recording the audio first and playing it after clicking on a button. It is my first time developing an app and it is a project for the university. I am also using Kotlin and Android Studio for the first time. I have tried to implement it with your visualizer, but the visualizer does not work, if i initialize it after i press a button. But i can hear my recorded audio in a low quality and not every time i press the play button. I have two buttons one is for recording and the other one stops the recording. The recorded audio is in the external storge of the phone. Can you help me to understanding it?

**Comment by dzolnai** [comment]
Hi!

I think you would be better off using the Visualizer widget of Android (https://developer.android.com/reference/android/media/audiofx/Visualizer).  That one is a lot easier to use, and you already have the required microphone permission.
