### ISSUE TITLE
How to set up count of bars?

### ISSUE THREAD

**Issue by Kolyall** [dzolnai/ExoVisualizer#6]
I want to make the view 32dp x 32dp and want to display for example only 5 bars, how to do it?

**Comment by dzolnai** [comment]
Hi!

By reducing the number of items in frequency band limits, you will get less bars, for example:
```
        private val FREQUENCY_BAND_LIMITS = arrayOf(
            80,
            630,
            4000,
            12500,
            20000
        )
```

If you see that one of the bars is too frequently used, you can adjust these numbers. But that ultimately is also dependent on the content you are playing - bass vs strings for example. 

You can make the view 32dp x 32dp by changing it's size:

``` 
<com.egeniq.exovisualizer.ExoVisualizer
        android:id="@+id/visualizer"
        android:layout_width="32dp"
        android:layout_height="32dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

But you will not see much on such a small scale. You might want to play around with the `maxConst` value to make it more sensitive:
```
private val maxConst = 10_000
```

**Comment by Kolyall** [comment]
Thanks!
