### ISSUE TITLE
Hamming Window equation

### ISSUE THREAD

**Issue by annhienktuit** [dzolnai/ExoVisualizer#8]
I thought that the expression of hamming window is: 
`w(n)=0.54-0.46*cos(2*pi*n/N) `

but in the `FFTBandView.kt` it was: 
` val windowed = raw * (0.54f + 0.46f * cos((currentFrequencyBandLimitIndex - m) * Math.PI / (m + 1))).toFloat()`

Can you explain it?

Thank you

**Comment by dzolnai** [comment]
Hi!
You are right, I have no idea where I got this version from :)
Pushed the fix

**Comment by annhienktuit** [comment]
Thank you
